= Pecenie krtkovej torty.

Ak mas priatelia, ktory onedlho bude oslavovat narodeniny, tak tento recept
je vhodny prave pre teba. Nebudes k tomu potrebovat ziadne zrucnosti v oblasti
pecenia narodeninovych tort.

=== Potrebne suroviny

==== Korpus
* 4 ks vajce
* 160 g cukor
* 140 g hladká múka
* 15 g kakao
* 1 KL prášok do pečiva DrOetker
* 50 ml olej
* 10 kvapiek rumová aróma DrOetker

==== Plnka
* 3 ks banán
* 2 hrste jahody
* 250 ml mlieko
* 1 ks Zlatý klas Dr Oetker
* 250 g tvaroh
* 1 ks vanilkový cukor DrOetker
* 1 ks kyslá smotana
* 1 ks šľahačková smotana
* 75 g čokoládové hobliny


=== Postup

Ako prve si uplecieme kakaovy korpus.

. Bielka vyšľaháme s cukrom. Postupne pridávame žĺtky, olej a podľa chuti pár kvapiek rumovej arómy.
Na záver primiešame múku s kypriacim práškom a kakaom.

. Pečieme asi 25 minút pri 170 stupňoch.

. Keď upečený koláč vychladne, lyžičkou vydlabene stred a cesto si odložíme. Prekrojené banány naukladáme na spodok cesta a na to dáme jahody.

Teraz sa mozme pustit do plnky.

. Najprv uvaríme zlatý klas s mliekom a necháme vychladnúť. Tvaroh vymiešame s vanilkovým cukrom, pridáme kyslú smotanu a vychladnutý puding. Potom pridáme čokoládové hobliny a na záver zľahka primiešame vyšľahanú šľahačku. Krém natrieme na ovocie.
. Plnku posypeme mrveničkou z vydlabanej torty.

=== Nutricne hodnoty

* link:https://www.kaloricketabulky.sk/krtkova-torta-dr-oetker[Kaloricke tabulky]
